server:
  port: 8080

logging:
  level:
    com.auth: DEBUG
    org.springframework.security: DEBUG


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080
          jwk-set-uri: http://localhost:7080/oauth2/token-info
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration
    schemas: public
    enabled: true
